In [1]:
import pandas as pd, numpy as np, matplotlib.pyplot as plt, seaborn as sb

In [2]:
df = pd.read_csv('../data/new_movie.csv')
df

,제목,제작 비용 ($),북미 박스오피스 수익 ($),전세계 박스오피스 수익 ($),개봉 주말 수익 ($),상영 등급,장르,상영관 수,상영 시간,개봉 연도,영화 유형
0,Avengers: Endgame,400000000,858373000.0,2.797801e+09,357115007.0,PG-13,Action,4662.0,181.0,2019,1
1,Pirates of the Caribbean: On Stranger Tides,379000000,241071802.0,1.045714e+09,90151958.0,PG-13,Adventure,4164.0,136.0,2011,1
2,Avengers: Age of Ultron,365000000,459005868.0,1.395317e+09,191271109.0,PG-13,Action,4276.0,141.0,2015,1
3,Star Wars Ep. VII: The Force Awakens,306000000,936662225.0,2.064616e+09,247966675.0,PG-13,Adventure,4134.0,136.0,2015,1
4,Avengers: Infinity War,300000000,678815482.0,2.048360e+09,257698183.0,PG-13,Action,4474.0,156.0,2018,1
...,...,...,...,...,...,...,...,...,...,...,...
486,The Incredibles,92000000,261441092.0,6.314411e+08,70467623.0,PG,Adventure,3933.0,115.0,2004,0
487,A Good Day to Die Hard,92000000,67349198.0,3.042492e+08,24834845.0,R,Action,3555.0,98.0,2013,0
488,The Alamo,92000000,22406362.0,2.391136e+07,9124701.0,PG-13,Western,2609.0,137.0,2004,0
489,Cutthroat Island,92000000,10017322.0,1.851732e+07,2371415.0,PG-13,Adventure,1619.0,122.0,1995,0
490,The Secret Life of Walter Mitty,91000000,58236838.0,1.878612e+08,12765508.0,PG,Adventure,2922.0,114.0,2013,0

In [4]:
df = df.loc[df['북미 박스오피스 수익 ($)'] != 0, :]

In [5]:
df['전세계/북미 수익 비율'] = (df['전세계 박스오피스 수익 ($)'] / df['북미 박스오피스 수익 ($)']).round(1)

In [6]:
df.describe()

,제작 비용 ($),북미 박스오피스 수익 ($),전세계 박스오피스 수익 ($),개봉 주말 수익 ($),상영관 수,상영 시간,개봉 연도,영화 유형,전세계/북미 수익 비율
count,4.910000e+02,4.910000e+02,4.910000e+02,4.910000e+02,491.000000,491.000000,491.000000,491.000000,491.000000
mean,1.494872e+08,1.753206e+08,4.779511e+08,5.429206e+07,3659.775967,121.865580,2011.358452,0.830957,3.501018
std,4.759424e+07,1.394589e+08,3.830213e+08,4.562877e+07,539.291514,22.303341,6.533261,0.935654,14.141535
min,9.100000e+07,3.114340e+05,7.561500e+04,4.855800e+04,30.000000,76.000000,1991.000000,0.000000,0.000000
25%,1.100000e+08,7.872882e+07,2.186231e+08,2.467904e+07,3394.000000,105.000000,2007.000000,0.000000,2.200000
50%,1.400000e+08,1.385409e+08,3.748258e+08,4.363974e+07,3711.000000,120.000000,2012.000000,0.000000,2.700000
75%,1.750000e+08,2.191196e+08,6.484352e+08,6.770120e+07,4058.500000,135.000000,2016.000000,2.000000,3.300000
max,4.000000e+08,9.366622e+08,2.910371e+09,3.571150e+08,4802.000000,210.000000,2022.000000,2.000000,315.400000

df['전세계/북미 수익 비율'].median() # max 값이 과도하게 높기 때문에 median 값을 일반적인 '전세계/북미 수익 비율'로 정의하기로 함